---
apiVersion: v1
kind: Service
metadata:
  name: ethereum-node
  namespace: ethereum
  labels:
    app: ethereum-node
    app.kubernetes.io/component: ethereum-workload
    app.kubernetes.io/instance: workload
    app.kubernetes.io/name: ethereum-node
    app.kubernetes.io/version: v1.0.0
    type: nodeport
spec:
  type: NodePort
  ports:
    - name: rpc
      port: 8545
      targetPort: 8545
      nodePort: 30845
      protocol: TCP
    - name: metrics
      port: 6060
      targetPort: 6060
      nodePort: 30606
      protocol: TCP
  selector:
    app: ethereum-node
    app.kubernetes.io/component: ethereum-workload
    app.kubernetes.io/instance: workload
    app.kubernetes.io/name: ethereum-node
    app.kubernetes.io/version: v1.0.0
  sessionAffinity: None
---
apiVersion: v1
kind: Service
metadata:
  name: ethereum-node-headless
  namespace: ethereum
  labels:
    app: ethereum-node
    app.kubernetes.io/component: ethereum-workload
    app.kubernetes.io/instance: workload
    app.kubernetes.io/name: ethereum-node
    app.kubernetes.io/version: v1.0.0
    type: headless
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: rpc
      port: 8545
      targetPort: 8545
      protocol: TCP
    - name: p2p
      port: 30303
      targetPort: 30303
      protocol: TCP
    - name: p2p-udp
      port: 30303
      targetPort: 30303
      protocol: UDP
    - name: metrics
      port: 6060
      targetPort: 6060
      protocol: TCP
  selector:
    app: ethereum-node
    app.kubernetes.io/component: ethereum-workload
    app.kubernetes.io/instance: workload
    app.kubernetes.io/name: ethereum-node
    app.kubernetes.io/version: v1.0.0
