---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ethereum-tls-cert
  namespace: ethereum
spec:
  secretName: ethereum-tls-cert
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  dnsNames:
    - "ethereum.example.com"
    - "*.ethereum.example.com"
