---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - vpa-crds.yaml
  - gateway-api-crds-v1.yaml
  - cert-manager-crds.yaml
  - prometheus-crds.yaml
  - sealed-secrets-crds.yaml
