---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: ethereum-gateway
  namespace: ethereum
  labels:
    app: ethereum-node
    app.kubernetes.io/component: ethereum-workload
    app.kubernetes.io/instance: workload
    app.kubernetes.io/name: ethereum-node
    app.kubernetes.io/version: v1.0.0
spec:
  gatewayClassName: gke-l7-global-external-managed
  listeners:
  - name: http-rpc
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: Same
  - name: https-rpc
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: Same
    tls:
      mode: Terminate
      certificateRefs:
      - name: ethereum-tls-cert
        namespace: ethereum
  - name: http-metrics
    port: 8080
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: Same
