---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gateway-class.yaml
  - ethereum-gateway.yaml
  - ethereum-routes.yaml

commonLabels:
  app.kubernetes.io/component: gateway-api
  app.kubernetes.io/instance: infrastructure
  app.kubernetes.io/name: ethereum-node
  app.kubernetes.io/version: v1.0.0 