---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vpa-recommender
  namespace: kube-system
  labels:
    app: vpa-recommender
    app.kubernetes.io/component: ethereum-infrastructure
    app.kubernetes.io/instance: base
    app.kubernetes.io/name: ethereum-node
    app.kubernetes.io/version: v1.0.0
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vpa-updater
  namespace: kube-system
  labels:
    app: vpa-updater
    app.kubernetes.io/component: ethereum-infrastructure
    app.kubernetes.io/instance: base
    app.kubernetes.io/name: ethereum-node
    app.kubernetes.io/version: v1.0.0
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vpa-admission-controller
  namespace: kube-system
  labels:
    app: vpa-admission-controller
    app.kubernetes.io/component: ethereum-infrastructure
    app.kubernetes.io/instance: base
    app.kubernetes.io/name: ethereum-node
    app.kubernetes.io/version: v1.0.0
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:metrics-reader
  labels:
    app.kubernetes.io/component: ethereum-infrastructure
    app.kubernetes.io/instance: base
    app.kubernetes.io/name: ethereum-node
    app.kubernetes.io/version: v1.0.0
rules:
  - apiGroups:
      - "metrics.k8s.io"
    resources:
      - pods
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:vpa-actor
  labels:
    app.kubernetes.io/component: ethereum-infrastructure
    app.kubernetes.io/instance: base
    app.kubernetes.io/name: ethereum-node
    app.kubernetes.io/version: v1.0.0
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - nodes
      - limitranges
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
      - events.k8s.io
    resources:
      - events
    verbs:
      - create
      - get
      - list
      - watch
      - patch
      - update
  - apiGroups:
      - "autoscaling.k8s.io"
    resources:
      - verticalpodautoscalers
      - verticalpodautoscalercheckpoints
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - "coordination.k8s.io"
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:vpa-admission-controller
  labels:
    app.kubernetes.io/component: ethereum-infrastructure
    app.kubernetes.io/instance: base
    app.kubernetes.io/name: ethereum-node
    app.kubernetes.io/version: v1.0.0
rules:
  - apiGroups:
      - "autoscaling.k8s.io"
    resources:
      - verticalpodautoscalers
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
      - configmaps
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:metrics-reader
  labels:
    app.kubernetes.io/component: ethereum-infrastructure
    app.kubernetes.io/instance: base
    app.kubernetes.io/name: ethereum-node
    app.kubernetes.io/version: v1.0.0
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:metrics-reader
subjects:
  - kind: ServiceAccount
    name: vpa-recommender
    namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:vpa-actor
  labels:
    app.kubernetes.io/component: ethereum-infrastructure
    app.kubernetes.io/instance: base
    app.kubernetes.io/name: ethereum-node
    app.kubernetes.io/version: v1.0.0
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:vpa-actor
subjects:
  - kind: ServiceAccount
    name: vpa-recommender
    namespace: kube-system
  - kind: ServiceAccount
    name: vpa-updater
    namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:vpa-admission-controller
  labels:
    app.kubernetes.io/component: ethereum-infrastructure
    app.kubernetes.io/instance: base
    app.kubernetes.io/name: ethereum-node
    app.kubernetes.io/version: v1.0.0
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:vpa-admission-controller
subjects:
  - kind: ServiceAccount
    name: vpa-admission-controller
    namespace: kube-system 