---
apiVersion: v1
kind: Service
metadata:
  name: vpa-admission-controller
  namespace: kube-system
  labels:
    app: vpa-admission-controller
spec:
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: vpa-admission-controller 