---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: monitoring
  labels:
    app.kubernetes.io/name: alertmanager
    app: managed-prometheus-alertmanager
spec:
  ports:
    - name: web
      port: 9093
      targetPort: 9093
      protocol: TCP
  selector:
    app.kubernetes.io/name: alertmanager
    app: managed-prometheus-alertmanager
