---
apiVersion: v1
kind: Secret
metadata:
  name: ethereum-tls-cert
  namespace: ethereum
  labels:
    app.kubernetes.io/component: ethereum-infrastructure
    app.kubernetes.io/instance: base
    app.kubernetes.io/name: ethereum-node
    app.kubernetes.io/version: v1.0.0
type: kubernetes.io/tls
data:
  tls.crt: ""
  tls.key: ""
