apiVersion: v1
kind: Service
metadata:
  name: sealed-secrets-controller
  namespace: sealed-secrets
  labels:
    app: sealed-secrets-controller
spec:
  selector:
    app: sealed-secrets-controller
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP 