apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: sealed-secrets-webhook
  labels:
    app: sealed-secrets-controller
webhooks:
  - name: sealed-secrets.bitnami.com
    clientConfig:
      service:
        name: sealed-secrets-controller
        namespace: sealed-secrets
        path: /v1/validate
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["secrets"]
    failurePolicy: Ignore
    sideEffects: None
    admissionReviewVersions: ["v1"] 